site_name: Smart Campus UIS

nav:
  - Home: index.md
  - GetStarted: core_usage.md
  - Arquitectura: arquitectura.md
  - ApiRest: ApiRestFull.md
  - Simulaciones: Simulaciones.md
  - AdminService: AdminService.md
  - Participantes: Participantes.md
  - Extension: Extension.md
  - Despliegue nueva arquitectura en Virtual Machine: Despliegue_SmartCampus_GCP.md

theme: readthedocs

